colors:
  primary:
    background: '0x22242d'
    foreground: '0xFFFFFF'

  normal:
    black:   '0x1F2229'
    red:     '0xEC0101'
    green:   '0x47D4B9'
    yellow:  '0xFF8A18'
    blue:    '0x277FFF'
    magenta: '0xD71655'
    cyan:    '0x05A1F7'
    white:   '0xa9a9a9'


  bright:
    black:   '0x1F2229'
    red:     '0xD41919'
    green:   '0x5EBDAB'
    yellow:  '0xFEA44C'
    blue:    '0x367bf0'
    magenta: '0xBF2E5D'
    cyan:    '0x49AEE6'
    white:   '0xFFFFFF'

font:
  normal:
    # patched font for powerline. install instructions at
    # https://powerline.readthedocs.io/en/master/installation.html#patched-fonts
    family: Inconsolata For Powerline
    style: Regular

  size: 13

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - tmux attach || tmux

window:
  position:
    x: 0
    y: 0

  # dimensions are full screen on lenovo monitor
  dimensions:
    columns: 213
    lines: 52
